apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "account-dataproduct"
  # namespace: broda-group-software
  title: "Account Data Product 01"
  description: "Broda Group Software sample account data product"
  # labels:
  # annotations:
  tags: ["account"]
  # links:
  links:
    - url: https://github.com/ericbroda/data-mesh-catalog/blob/main/dataproducts/account/specification-license.yaml
      title: This is a sample link

spec:
  # Reserved fields
  type: data-product
  lifecycle: "experimental"
  owner: "user:eric.broda"
  system: "customer-analytics"
  subcomponentOf: "parent-1"
  providesApis: ["somePublishedAPI"]
  consumesApis: ["someConsumedAPI"]
  dependsOn: ["component:party-dataproduct", "component:product-dataproduct", "component:transaction-dataproduct"]

  # Custom fields
  # GitHub REST API: "https://api.github.com/repos/ericbroda/data-mesh-product-new/contents/specification-license.yaml"
  licenseSpecification: "https://github.com/ericbroda/data-mesh-catalog/blob/main/dataproducts/account/specification-license.yaml"
  apiSpecification: "https://github.com/ericbroda/data-mesh-catalog/blob/main/dataproducts/account/specification-api.yaml"
  querySpecification: "https://github.com/ericbroda/data-mesh-catalog/blob/main/dataproducts/account/specification-query.yaml"
  eventSpecification: "https://github.com/ericbroda/data-mesh-catalog/blob/main/dataproducts/account/specification-event.yaml"
  # Sample for schemas: https://datahubproject.io/docs/metadata-service (Retrieving Entity Aspects section)
  metadataSpecification: "https://github.com/ericbroda/data-mesh-catalog/blob/main/dataproducts/account/specification-metadata.json"
