openapi: 3.0.1
servers:
  - url: http://brodagroupsoftware/v1
info:
  title: "Transaction Data Transaction API"
  description: "Transaction Data Transaction API to access transaction data"
  contact:
    name: "eric.broda"
    email: contact@brodagroupsoftware.com
  version: v0.0.1
paths:
  /discover:
    get:
      summary: Discover endpoint
      operationId: discoverGET
      tags:
        - discover
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
  /observe:
    get:
      summary: Observe endpoint
      operationId: observeGET
      tags:
        - observe
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
  /usage:
    get:
      summary: Usage endpoint
      operationId: usageGET
      tags:
        - usage
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
  /logs:
    get:
      summary: Logs endpoint
      operationId: logsGET
      tags:
        - logs
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
  /alerts:
    get:
      summary: Alerts endpoint
      operationId: alertsGET
      tags:
        - alerts
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: string
