# ---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: partyDomain
  description: partyDomain
spec:
  owner: guest
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: accountDomain
  description: accountDomain
spec:
  owner: guest
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: productDomain
  description: productDomain
spec:
  owner: guest
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: transactionDomain
  description: transactionDomain
spec:
  owner: guest
---
