apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "party-dataproduct"
  # namespace: broda-group-software
  title: "Party Data Product 01"
  description: "Broda Group Software sample party data product"
  # labels:
  # annotations:
  tags: ["customer", "party", "prospect"]
  # links:
spec:
  # Reserved fields
  type: data-product
  lifecycle: "experimental"
  owner: "user:guest"
  # owner: "user:eric.broda"
  system: "customer-analytics"
  subcomponentOf: "parent-1"
  providesApis: ["somePublishedAPI"]
  consumesApis: ["someConsumedAPI"]
  dependsOn: ["component:account-dataproduct", "component:product-dataproduct", "component:transaction-dataproduct"]

  # Custom fields
  # GitHub REST API: "https://api.github.com/repos/ericbroda/data-mesh-product-new/contents/specification-license.yaml"
  licenseSpecification: "https://github.com/ericbroda/data-mesh-catalog/blob/main/dataproducts/party/specification-license.yaml"
  apiSpecification: "https://github.com/ericbroda/data-mesh-catalog/blob/main/dataproducts/party/specification-api.yaml"
  querySpecification: "https://github.com/ericbroda/data-mesh-catalog/blob/main/dataproducts/party/specification-query.yaml"
  eventSpecification: "https://github.com/ericbroda/data-mesh-catalog/blob/main/dataproducts/party/specification-event.yaml"
  # Sample for schemas: https://datahubproject.io/docs/metadata-service (Retrieving Entity Aspects section)
  schemaSpecification: "https://github.com/ericbroda/data-mesh-catalog/blob/main/dataproducts/party/specification-schema.json"
