# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: customer-analytics
spec:
  owner: eric.broda
  domain: party-domain
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: customer-web
spec:
  owner: eric.broda
  domain: party-domain
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: customer-advisor
spec:
  owner: eric.broda
  domain: party-domain
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: customer-mobile
spec:
  owner: eric.broda
  domain: party-domain
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name:core-banking-accounts
spec:
  owner: eric.broda
  domain: account-domain
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name:core-banking-products
spec:
  owner: eric.broda
  domain: product-domain
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name:core-banking-transactions
spec:
  owner: eric.broda
  domain: transaction-domain
---